apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata: |
  name: {{ template "kubelab-chart.fullname" . }}-deployment
spec:
  selector:
    matchLabels:
      app: {{ template "kubelab-chart.fullname" . }}
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: {{ template "kubelab-chart.fullname" . }}
    spec:
      containers:
      - name: {{ .Values.ContainerName }}
        image: nginx:1.7.9
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata: |
  name: {{ template "kubelab-chart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "kubelab-chart.fullname" . }}
  ports:
  - port: 8081
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata: |
  name: {{ template "kubelab-chart.fullname" . }}-ingress
spec:
  backend:
    serviceName: {{ template "kubelab-chart.fullname" . }}-service
    servicePort: 8081
  rules:
  - host: 
    http:
      paths:
      - path: /test
        backend:
          serviceName: {{ template "kubelab-chart.fullname" . }}-service
          servicePort: 8081
